server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.22.118:3307/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

